User can log out
CraftAcademy/legacy_code_june19_team2 pull request #17
Opened 2019-07-07 10:04 UTC by pedrocbras

Minor refactoring on Steps files
Adds tests for user-can-log-out feature

2019-07-07 11:38 UTC, tochman requested changes

2019-07-07 11:38 UTC, tochman commented on features/step_definitions/basic_steps.rb
> +end
I'm not sure about naming in this step definition...

2019-07-07 11:38 UTC, tochman commented on features/user_can_log_out.feature
> +    And I click "Log in"
I would use warden helpers here, and not go through the ui

2019-07-07 11:38 UTC, tochman commented on features/user_can_log_out.feature
> +    Then I should see "Signed in successfully."
Please avoid assertions in backgroud. No need or purpose

2019-07-07 16:04 UTC, pedrocbras commented on features/user_can_log_out.feature
> +    Then I should see "Signed in successfully."
Makes total sense! Removed.

2019-07-07 16:07 UTC, pedrocbras commented on features/step_definitions/basic_steps.rb
> +end
This block was created by Faraz on another feature that was already merged. I just changed it to the basic steps file because they had it in another separate file they created for that specific feature, and in order to be consistent I moved it to the file where the other features' steps are.

2019-07-07 16:15 UTC, pedrocbras commented on features/user_can_log_out.feature
> +    And I click "Log in"
Never heard about warden helpers before to be honest! Going to look it up and try to implement it.

2019-07-07 19:59 UTC, pedrocbras commented on features/user_can_log_out.feature
> +    And I click "Log in"
Warden helpers added!

2019-07-08 07:45 UTC, oliverochman commented on features/step_definitions/basic_steps.rb
> +    @receiver = User.find_by(name: email[:receiver])
do you need to use an instance variable here?

2019-07-08 07:45 UTC, oliverochman commented on features/step_definitions/basic_steps.rb
> +Given("the following messages exist") do |table|
Why was this step def added in this PR?

2019-07-08 08:05 UTC, pedrocbras commented on features/step_definitions/basic_steps.rb
> +    @receiver = User.find_by(name: email[:receiver])
They were in a separate feature file, and I added them to the basic_steps file where we had all the steps for all the features. These code blocks were writen by Faraz actually, and they were already merged in another PR. But I just moved them in a refactoring attempt.

2019-07-08 08:05 UTC, pedrocbras commented on features/step_definitions/basic_steps.rb
> +Given("the following messages exist") do |table|
Because I moved them. They were in a separate feature file, and I added them to the basic_steps file where we had all the steps for all the features. These code blocks were writen by Faraz actually, and they were already merged in another PR. But I just moved them in a refactoring attempt.

2019-07-08 09:36 UTC, oliverochman commented on features/step_definitions/basic_steps.rb
> +    @receiver = User.find_by(name: email[:receiver])
I understand, but can I get an answer to my question?

2022-03-22 19:24 UTC, closed without merging